kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/fanux/dashboard

steps:
- name: install
  image: golang:1.11.3
  commands:
    - go get github.com/cuisongliu/sealbuild
    - cp $GOPATH/bin/sealbuild .
    - ls -l /usr/local/bin
- name: build
  image: docker
  commands:
    - dockerd &
    - docker version
    - docker info

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: kube${DRONE_TAG}.tar.gz
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag
