name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        env
        docker info
        docker version
        git clone https://github.com/cuisongliu/sealbuild.git
        cd sealbuild
        export GO111MODULE=on && export GOPROXY=https://goproxy.io && cd src/ && export GOOS=linux && export GOARCH=amd64 && go build -o ../sealbuild -v && chmod a+x ../sealbuild
        ./sealbuild -f config.ini

